name: dissertation2
channels:
  - conda-forge
dependencies:
  - absl-py=0.13.0=pyhd8ed1ab_0
  - appnope=0.1.2=py38h10201cd_1
  - argh=0.26.2=pyh9f0ad1d_1002
  - argon2-cffi=20.1.0=py38hea4295b_2
  - async_generator=1.10=py_0
  - attrs=21.2.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - bleach=4.1.0=pyhd8ed1ab_0
  - brotlipy=0.7.0=py38hea4295b_1001
  - ca-certificates=2021.5.30=h4653dfc_0
  - certifi=2021.5.30=py38h10201cd_0
  - cffi=1.14.6=py38hc67bbb8_1
  - chardet=4.0.0=py38h10201cd_1
  - charset-normalizer=2.0.0=pyhd8ed1ab_0
  - click=8.0.1=py38h10201cd_0
  - configparser=5.0.2=pyhd8ed1ab_0
  - cryptography=3.4.7=py38h3c0dae5_0
  - debugpy=1.4.1=py38h6f2b01f_0
  - decorator=5.1.0=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - docker-pycreds=0.4.0=py_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - freetype=2.10.4=h17b34a0_1
  - future=0.18.2=py38h10201cd_3
  - gitdb=4.0.7=pyhd8ed1ab_0
  - gitpython=3.1.24=pyhd8ed1ab_0
  - gql=0.1.0=py_0
  - graphql-core=3.1.6=pyhd8ed1ab_0
  - idna=3.1=pyhd3deb0d_0
  - importlib-metadata=4.8.1=py38h10201cd_0
  - ipykernel=6.4.1=py38h2cb4d76_0
  - ipython=7.27.0=py38h2cb4d76_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.6.5=pyhd8ed1ab_0
  - jbig=2.1=h3422bc3_2003
  - jedi=0.18.0=py38h10201cd_2
  - jinja2=3.0.1=pyhd8ed1ab_0
  - jpeg=9d=h27ca646_0
  - jsonschema=3.2.0=pyhd8ed1ab_3
  - jupyter=1.0.0=py38h10201cd_6
  - jupyter_client=7.0.3=pyhd8ed1ab_0
  - jupyter_console=6.4.0=pyhd8ed1ab_0
  - jupyter_core=4.8.1=py38h10201cd_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_widgets=1.0.2=pyhd8ed1ab_0
  - lcms2=2.12=had6a04f_0
  - lerc=2.2.1=h9f76cd9_0
  - libblas=3.9.0=11_osxarm64_openblas
  - libcblas=3.9.0=11_osxarm64_openblas
  - libcxx=12.0.1=h168391b_0
  - libdeflate=1.7=h27ca646_5
  - libffi=3.4.2=hbdafb3b_1
  - libgfortran=5.0.0.dev0=11_0_1_hf114ba7_23
  - libgfortran5=11.0.1.dev0=hf114ba7_23
  - liblapack=3.9.0=11_osxarm64_openblas
  - libopenblas=0.3.17=openmp_h5dd58f0_1
  - libpng=1.6.37=hf7e6567_2
  - libprotobuf=3.16.0=hccf11d3_0
  - libsodium=1.0.18=h27ca646_1
  - libtiff=4.3.0=hc6122e1_1
  - libwebp-base=1.2.1=h3422bc3_0
  - llvm-openmp=12.0.1=hf3c4609_1
  - lz4-c=1.9.3=hbdafb3b_1
  - markupsafe=2.0.1=py38hea4295b_0
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - mistune=0.8.4=py38hea4295b_1004
  - nbclient=0.5.4=pyhd8ed1ab_0
  - nbconvert=6.1.0=py38h10201cd_1
  - nbformat=5.1.3=pyhd8ed1ab_0
  - ncurses=6.2=h9aa5885_4
  - nest-asyncio=1.5.1=pyhd8ed1ab_0
  - ninja=1.10.2=h4d860bb_0
  - notebook=6.4.4=pyha770c72_0
  - numpy=1.21.2=py38hbf7bb01_0
  - nvidia-ml=7.352.0=py_0
  - olefile=0.46=pyh9f0ad1d_1
  - openjpeg=2.4.0=h062765e_1
  - openssl=1.1.1l=h3422bc3_0
  - packaging=21.0=pyhd8ed1ab_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.2=pyhd8ed1ab_0
  - pathtools=0.1.2=py_1
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=8.3.2=py38h02acf36_0
  - pip=21.2.4=pyhd8ed1ab_0
  - prometheus_client=0.11.0=pyhd8ed1ab_0
  - promise=2.2.1=py_0
  - prompt-toolkit=3.0.20=pyha770c72_0
  - prompt_toolkit=3.0.20=hd8ed1ab_0
  - psutil=5.8.0=py38hea4295b_1
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.10.0=pyhd8ed1ab_0
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyrsistent=0.17.3=py38hea4295b_2
  - pysocks=1.7.1=py38h10201cd_3
  - python=3.8.12=hab31e5c_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pytorch-cpu=1.9.0=cpu_py38hd610c6a_2
  - pyyaml=5.4.1=py38hea4295b_1
  - pyzmq=22.3.0=py38h51b17a6_0
  - readline=8.1=hedafd6a_0
  - requests=2.26.0=pyhd8ed1ab_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - sentry-sdk=1.4.1=pyhd8ed1ab_0
  - setuptools=58.0.4=py38h10201cd_0
  - shortuuid=1.0.1=py_0
  - six=1.16.0=pyh6c4a22f_0
  - sleef=3.5.1=h27ca646_1
  - smmap=3.0.5=pyh44b312d_0
  - sqlite=3.36.0=h72a2b83_1
  - subprocess32=3.5.4=py_1
  - terminado=0.12.1=py38h10201cd_0
  - testpath=0.5.0=pyhd8ed1ab_0
  - tk=8.6.11=he1e0b03_1
  - torchvision=0.10.0=py38h4ddca67_0_cpu
  - tornado=6.1=py38hea4295b_1
  - traitlets=5.1.0=pyhd8ed1ab_0
  - typing=3.10.0.0=pyhd8ed1ab_0
  - typing_extensions=3.10.0.0=pyha770c72_0
  - urllib3=1.26.7=pyhd8ed1ab_0
  - wandb=0.12.1=pyhd8ed1ab_0
  - watchdog=0.9.0=py_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - wheel=0.37.0=pyhd8ed1ab_1
  - widgetsnbextension=3.5.1=py38h10201cd_4
  - xz=5.2.5=h642e427_1
  - yaml=0.2.5=h642e427_0
  - zeromq=4.3.4=hbdafb3b_1
  - zipp=3.5.0=pyhd8ed1ab_0
  - zlib=1.2.11=h31e879b_1009
  - zstd=1.5.0=h861e0a7_0
  - pip:
    - protobuf==3.18.0
    - tensorboardx==2.4
    - torch==1.9.0
prefix: /opt/homebrew/Caskroom/miniforge/base/envs/dissertation2
